### PR TITLE
fix: eip712 support for pubkey any messages

### PR DESCRIPTION
**Pull request by hanchon**
Closes: #XXX

## Description
Most messages with EIP712 are working fine, but the code is not working if some values that are not the cosmos transaction itself, are contained inside a `proto.Any` object.

The issue is that when we create read the transactions values, they are parsed using the JSON lib, for example, for public keys it returns the base64 representation of the pubkey as a `string`.

When the lib generates the types for the EIP712 message, it uses codec.UnpackAny if the message is contained inside a `proto.Any` object it will return {type:string, value:...} instead of the expected `string`

For now the only value that I found that is sent as a `proto.Any` message is the pubkey, but I need to review the rest of the cosmos-sdk messages

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by zmanian** [comment]
This PR would close
https://github.com/tharsis/evmos/issues/545

**Comment by fedekunze** [comment]
@zmanian we also would need to remove the single signature check as @tony-iqlusion mentioned

**Comment by zmanian** [comment]
Iqlusion would be willing to join the validator set with a single sig ledger backed key.

**Comment by zmanian** [comment]
It's a partial fix for the issue.

**Comment by facs95** [comment]
Replaced by this https://github.com/evmos/ethermint/pull/1283

**Pull request closed without merging**
