### PR TITLE
tests: add benchmark tests setup

### PR DESCRIPTION
**Pull request by Vvaradinov**
Closes: #XXX

## Description
This PR adds a new the initial setup for benchmark testing `params` getting and setting. Benchmark tests can be executed with the following command: `benchmark=true go test -bench=. -count 15` setting `benchmark=true` in order to avoid conflicting with our Gingko test setup.

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Review by MalteHerrmann — COMMENTED** [review]
Great work @Vvaradinov! Tested this an it works as expected.

My suggestion would be to set up corresponding Makefile command(s) as well to have a basis for added tests in the future: `make test-benchmark`.

Let me make a PR with a suggestion and we can discuss further.

**Comment by Vvaradinov** [comment]
@MalteHerrmann we would need to create a new CI pipeline for this as well and make sure all the raw records are stored somewhere so we can compare later.

**Comment by fedekunze** [comment]
@Vvaradinov that's what the gobencher CI is for

**Comment by fedekunze** [comment]
> EDIT: Just seen, that we already have `make benchmark` - we should work from there.

@MalteHerrmann seems to be misconfigured as it also runs unit tests. Let's fix the benchmark config in a separate PR.

`benchmark=true go test -bench=. -count 15 ./...` is failing because of unrelated tests

**Review by fedekunze — APPROVED** [review]

**Comment by MalteHerrmann** [comment]
https://github.com/Mergifyio backport release/v0.21.x

**Pull request merged**
