### PR TITLE
fix: Bump Go-Ethereum dependency to 1.10.26

### PR DESCRIPTION
**Pull request by austinchandra**
Closes: #XXX

## Description

Release Notes: https://github.com/ethereum/go-ethereum/releases/tag/v1.10.26

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by facs95** [comment]
We need to look at the changelog on Geth and implement the respective changes on our side. 
This two are the most relevant I think
- https://github.com/ethereum/go-ethereum/pull/26054
- https://github.com/ethereum/go-ethereum/pull/26064

**Review by fedekunze — APPROVED** [review]
LGTM, pending changelog entry

**Comment by austinchandra** [comment]
I don't think the changes apply @facs95, although please correct if wrong.

**Comment by facs95** [comment]
I am not 100% sure but I do think this change applies https://github.com/ethereum/go-ethereum/pull/26054

**Comment by austinchandra** [comment]
> I am not 100% sure but I do think this change applies [ethereum/go-ethereum#26054](https://github.com/ethereum/go-ethereum/pull/26054)

Our `Filter` object is constructed [differently](https://github.com/evmos/ethermint/blob/39309e0b21666b25b1fef1a89a5b8f0496d46084/rpc/namespaces/ethereum/eth/filters/filters.go#L30), and references the block hash through the `FilterCriteria` object, where it's already [stored](https://github.com/ethereum/go-ethereum/blob/10347c6b54d5b28a2e71d9c4993e7f44b0a359c3/interfaces.go#L156) as a pointer.

What would we change here?

**Comment by facs95** [comment]
Back in my computer now- just checked and you are right we dont need to change anything on our side for this. Will approve and merge

**Review by facs95 — APPROVED** [review]

**Review by Kalliingi — COMMENTED** [review]
Kalli

**Pull request merged**
