### PR TITLE
chore: update proto make commands

### PR DESCRIPTION
**Pull request by MalteHerrmann**
This PR updates and cleans up the `make` commands targeting the Protobuf files. 

Specifically, it:
- Updates the `make` commands to use the ~~`cosmos/proto-builder`~~ `tendermintdev/sdk-proto-gen` v0.7 docker image
- adds hint to delete docker containers for possible problems during execution
- ~~commits resulting changes from executing `make proto-all` with the `cosmos/proto-builder` docker container~~

### CODE REVIEW

**Comment by MalteHerrmann** [comment]
Currently looking into failing tests..

**Review by GAtom22 — COMMENTED** [review]
Maybe is a problem on my end, but when I run the commands `make proto-gen` or `make proto-swagger-gen` the process hangs. It spins up the docker image alright, but then it does not execute the shell script. If I run the corresponding scripts directly, it works OK.

In my case, this is solved replacing the commands with
```
proto-gen:
	@echo "Generating Protobuf files"
	$(protoImage) && ./scripts/protocgen.sh

proto-swagger-gen:
	@echo "Generating Protobuf Swagger"
	$(protoImage) && ./scripts/protoc-swagger-gen.sh
```

But maybe that does not work on macOS. If that's the case, we could add an OS check to run one or the other

**Update**: making this change will not do what is intended, that is running the script inside the docker container. As mentioned in the comment below, this was solved by adding the `--network host` flag to the `docker run` command.

**Comment by MalteHerrmann** [comment]
> Maybe is a problem on my end, but when I run the commands `make proto-gen` or `make proto-swagger-gen` the process hangs. 

@GAtom22 can you check if you can execute the scripts on the `cosmos-sdk`? They're using the same commands: https://github.com/cosmos/cosmos-sdk/blob/e2ae2bb551e2c723b52da4b813b194060014d288/Makefile#L400

@facs95 I remember you mentioning that it was stuck for you as well, but then finally worked?

**Review by GAtom22 — APPROVED** [review]
Test ACK! Great work @MalteHerrmann!

**Review by Vvaradinov — APPROVED** [review]
Tested and getting the expected proto generated files and the swagger docs. Great work!

**Review by ramacarlucho — APPROVED** [review]

**Review by facs95 — APPROVED** [review]

**Pull request merged**
