### PR TITLE
fix(rpc): wrong block number in debug trace related api

### PR DESCRIPTION
**Pull request by mmsqe**
Closes: #XXX

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by VictorTrustyDev** [comment]
block height already minus by one in rpc
https://github.com/evmos/ethermint/blob/main/rpc/backend/tracing.go#L109-L114

**Comment by mmsqe** [comment]
> block height already minus by one in rpc
> 
> https://github.com/evmos/ethermint/blob/57ed355c985d9f3116aba6aabfa2ee0f3f38e966/rpc/backend/tracing.go#L110-L114
> 
> Oh no, so currently it keep minus by one in grpc so actually minus by 2? If calling via API debug_traceTransaction?

**Comment by mmsqe** [comment]
> block height already minus by one in rpc
> 
> https://github.com/evmos/ethermint/blob/57ed355c985d9f3116aba6aabfa2ee0f3f38e966/rpc/backend/tracing.go#L110-L114
> 
> Oh no, so currently it keep minus by one in grpc so actually minus by 2? If calling via API debug_traceTransaction?

Fixing BlockNumber from [request](https://github.com/evmos/ethermint/blob/57ed355c985d9f3116aba6aabfa2ee0f3f38e966/rpc/backend/tracing.go#L98), no need minus 1

**Comment by yihuang** [comment]
The `contextHeight` is minus one to get to the state of block beginning, but the block number pass to evm context should not minus one.

**Review by 4rgon4ut — APPROVED** [review]
LGTM! Good job @mmsqe

**Comment by facs95** [comment]
Hey @yihuang have you ever seen the `fixed-output derivation..` nix issues that are making the integration tests fail?

**Review by fedekunze — APPROVED** [review]

**Pull request merged**
