### PR TITLE
Remove unbound labels from added custom tendermint metrics

### PR DESCRIPTION
**Pull request by v-homsi**
Closes: #1435 

## Description

This PR removes the labels `from` and `to` as these result in unbound cardinality as it will keep creating new metrics with every new `from` and `to` values received in the node.

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Review by 08d2 — APPROVED** [review]

**Comment by fedekunze** [comment]
@v-homsi is this R4R?

**Comment by v-homsi** [comment]
> @v-homsi is this R4R?

The PR should fix the issue. It will remove the label causing the unbound cardinality. I was not able to test it though as there might be something wrong with adding custom metrics using the telemetry package from cosmos. 

I tried the config suggested in [here](https://github.com/evmos/evmos/issues/1050#issuecomment-1316068327)
I also tried querying http://localhost:1317/metrics which returns method not implemented. 

I put some log traces before this [line](https://github.com/evmos/ethermint/blob/main/x/evm/keeper/msg_server.go#L70) and I was able to see the log but for some reason the metrics are not showing.

@facs95 @danburck @08d2  Any idea how I could test this?

**Comment by 08d2** [comment]
@v-homsi You'll want to enable Prometheus metrics [as described here](https://github.com/evmos/evmos/issues/1050#issuecomment-1316068327) and then query `localhost:26660/metrics`. My gut instinct for a test would be to start a "default" node with Prometheus enabled as above, do whatever work is necessary to create the metrics under discussion, and then query the metrics endpoint and make sure the response doesn't include addresses as described in the issue.

**Comment by v-homsi** [comment]
> @v-homsi You'll want to enable Prometheus metrics [as described here](https://github.com/evmos/evmos/issues/1050#issuecomment-1316068327) and then query `localhost:26660/metrics`. My gut instinct for a test would be to start a "default" node with Prometheus enabled as above, do whatever work is necessary to create the metrics under discussion, and then query the metrics endpoint and make sure the response doesn't include addresses as described in the issue.

@facs95 and myself were able to confirm that there's a regression in main with regards to the metrics exposed. I was able to test this issue and fix with ethermint v0.19.3.

Metrics before fix (keep increasing):
```bash
# HELP tx_msg_ethereum_tx_gas_limit_per_gas_used tx_msg_ethereum_tx_gas_limit_per_gas_used
# TYPE tx_msg_ethereum_tx_gas_limit_per_gas_used gauge
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="create"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0x00ba27f8CAE54bC38A67BE0a1077Bc427D816304"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0x067600911EE41D2FbE5B1dD6F30CaE4C5A002E70"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0x1DA2F63e496F49E43c59087710126DAB1649f795"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0x205Bb4e8eD5a9BF9Ab9cE2D54a86aa13e7aC6539"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0x34a5FBea2137ed839b52F9F9d0e4cBe58fdE5485"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0x579d337e0590a434E58cC286C9Dd9209c4fE9C22"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0x5fDc83C9a7650e480bbcFEdC5f5057B20905cB10"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0x6c324BfAF37ACcD07Bb54d281B2A0D2bf54Ff9A6"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0x7063e1dfd17265EedB3C3bf3496296e82f0B00b0"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0x794F66845dB2e3B1Ca39d31A2Ab8213685b47840"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0x7A044ff36DC6fA523dc9df378E5a6f35d6B8565F"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xA201ABDb614dc7a1565b62F08858477112766985"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xCF69147202f78C282c56FE1659F1F6B0A2E662c8"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xCedad0fF142a99b7c7C2709c1a3B8a28A7f72f03"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xD8eE4E625190bcb69D4c131d31213B2dbC1DE9A4"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xF1904bCD14357ab5166bfe6535f304e07fCf15A3"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xa033b23A6Fec69961f68ab81A263C2d25775e1ec"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xccC51754c509FeEC9d05C80f2526bBD545e38ab1"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xd76b3561DC6E01253f1d4E7F08AdE96196540CE9"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xdd3a41B13197ba65583afC81494A8A781433636d"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xe9e2A0Afe411bc9072145d76a12ce0B638A9E29C"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xf0010bBA471e5Fa17e10859278223D5420B90cAC"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",to="0xf8701Cb9ef494d5378B9186013770654752f8AFf"} 1
# HELP tx_msg_ethereum_tx_gas_used_total tx_msg_ethereum_tx_gas_used_total
# TYPE tx_msg_ethereum_tx_gas_used_total counter
tx_msg_ethereum_tx_gas_used_total{execution="create"} 1.697409e+06
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0x00ba27f8CAE54bC38A67BE0a1077Bc427D816304"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0x067600911EE41D2FbE5B1dD6F30CaE4C5A002E70"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0x1DA2F63e496F49E43c59087710126DAB1649f795"} 1.02587176e+08
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0x205Bb4e8eD5a9BF9Ab9cE2D54a86aa13e7aC6539"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0x34a5FBea2137ed839b52F9F9d0e4cBe58fdE5485"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0x579d337e0590a434E58cC286C9Dd9209c4fE9C22"} 1.36575403e+08
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0x5fDc83C9a7650e480bbcFEdC5f5057B20905cB10"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0x6c324BfAF37ACcD07Bb54d281B2A0D2bf54Ff9A6"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0x7063e1dfd17265EedB3C3bf3496296e82f0B00b0"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0x794F66845dB2e3B1Ca39d31A2Ab8213685b47840"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0x7A044ff36DC6fA523dc9df378E5a6f35d6B8565F"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xA201ABDb614dc7a1565b62F08858477112766985"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xCF69147202f78C282c56FE1659F1F6B0A2E662c8"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xCedad0fF142a99b7c7C2709c1a3B8a28A7f72f03"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xD8eE4E625190bcb69D4c131d31213B2dbC1DE9A4"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xF1904bCD14357ab5166bfe6535f304e07fCf15A3"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xa033b23A6Fec69961f68ab81A263C2d25775e1ec"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xccC51754c509FeEC9d05C80f2526bBD545e38ab1"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xd76b3561DC6E01253f1d4E7F08AdE96196540CE9"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xdd3a41B13197ba65583afC81494A8A781433636d"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xe9e2A0Afe411bc9072145d76a12ce0B638A9E29C"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xf0010bBA471e5Fa17e10859278223D5420B90cAC"} 21000
tx_msg_ethereum_tx_gas_used_total{execution="call",to="0xf8701Cb9ef494d5378B9186013770654752f8AFf"} 6.1502506e+07
# HELP tx_msg_ethereum_tx_total tx_msg_ethereum_tx_total
# TYPE tx_msg_ethereum_tx_total counter
tx_msg_ethereum_tx_total{execution="create"} 3
tx_msg_ethereum_tx_total{execution="call",to="0x00ba27f8CAE54bC38A67BE0a1077Bc427D816304"} 1
tx_msg_ethereum_tx_total{execution="call",to="0x067600911EE41D2FbE5B1dD6F30CaE4C5A002E70"} 1
tx_msg_ethereum_tx_total{execution="call",to="0x1DA2F63e496F49E43c59087710126DAB1649f795"} 824
tx_msg_ethereum_tx_total{execution="call",to="0x205Bb4e8eD5a9BF9Ab9cE2D54a86aa13e7aC6539"} 1
tx_msg_ethereum_tx_total{execution="call",to="0x34a5FBea2137ed839b52F9F9d0e4cBe58fdE5485"} 1
tx_msg_ethereum_tx_total{execution="call",to="0x579d337e0590a434E58cC286C9Dd9209c4fE9C22"} 1097
tx_msg_ethereum_tx_total{execution="call",to="0x5fDc83C9a7650e480bbcFEdC5f5057B20905cB10"} 1
tx_msg_ethereum_tx_total{execution="call",to="0x6c324BfAF37ACcD07Bb54d281B2A0D2bf54Ff9A6"} 1
tx_msg_ethereum_tx_total{execution="call",to="0x7063e1dfd17265EedB3C3bf3496296e82f0B00b0"} 1
tx_msg_ethereum_tx_total{execution="call",to="0x794F66845dB2e3B1Ca39d31A2Ab8213685b47840"} 1
tx_msg_ethereum_tx_total{execution="call",to="0x7A044ff36DC6fA523dc9df378E5a6f35d6B8565F"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xA201ABDb614dc7a1565b62F08858477112766985"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xCF69147202f78C282c56FE1659F1F6B0A2E662c8"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xCedad0fF142a99b7c7C2709c1a3B8a28A7f72f03"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xD8eE4E625190bcb69D4c131d31213B2dbC1DE9A4"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xF1904bCD14357ab5166bfe6535f304e07fCf15A3"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xa033b23A6Fec69961f68ab81A263C2d25775e1ec"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xccC51754c509FeEC9d05C80f2526bBD545e38ab1"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xd76b3561DC6E01253f1d4E7F08AdE96196540CE9"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xdd3a41B13197ba65583afC81494A8A781433636d"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xe9e2A0Afe411bc9072145d76a12ce0B638A9E29C"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xf0010bBA471e5Fa17e10859278223D5420B90cAC"} 1
tx_msg_ethereum_tx_total{execution="call",to="0xf8701Cb9ef494d5378B9186013770654752f8AFf"} 494
```

Metrics after the fix (constant):
```bash
# HELP tx_msg_ethereum_tx_gas_limit_per_gas_used tx_msg_ethereum_tx_gas_limit_per_gas_used
# TYPE tx_msg_ethereum_tx_gas_limit_per_gas_used gauge
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="call",tx_type="2"} 1
tx_msg_ethereum_tx_gas_limit_per_gas_used{execution="create",tx_type="2"} 1
# HELP tx_msg_ethereum_tx_gas_used_total tx_msg_ethereum_tx_gas_used_total
# TYPE tx_msg_ethereum_tx_gas_used_total counter
tx_msg_ethereum_tx_gas_used_total{execution="call",tx_type="2"} 1.01240188e+08
tx_msg_ethereum_tx_gas_used_total{execution="create",tx_type="2"} 565803
# HELP tx_msg_ethereum_tx_total tx_msg_ethereum_tx_total
# TYPE tx_msg_ethereum_tx_total counter
tx_msg_ethereum_tx_total{execution="call",tx_type="2"} 819
tx_msg_ethereum_tx_total{execution="create",tx_type="2"} 1
```

@facs95 @fedekunze This PR is ready to be reviewed and merged. @facs95 will be investigating the regression with regards to why the metrics are not exposed in main. 

Thanks @08d2

**Review by facs95 — APPROVED** [review]

**Pull request merged**
